name: UnitTests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.9.10]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r code/test/requirements.txt

      - name: Run unit tests
        run: |
          bash code/lib/run_tests.sh

      - name: Get test coverage
        run: |
          bash code/lib/get_test_coverage.sh
          ls -la code/lib

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: code/lib/.coverage
